---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-sa
  namespace: face-it-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager-role
  namespace: face-it-workers
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server-pod-manager-binding
  namespace: face-it-workers
subjects:
- kind: ServiceAccount
  name: api-server-sa
  namespace: face-it-api
roleRef:
  kind: Role
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: face-it-workers
